# Generated by Django 5.2 on 2025-05-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0002_alter_userprofile_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="xrpl_address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="xrpl_seed",
            field=models.CharField(max_length=255),
        ),
    ]
