# Generated by Django 5.2 on 2025-04-07 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trip_code",
                    models.CharField(
                        help_text="每個行程的唯一識別碼，例：T001、T002等",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="請輸入行程的名稱，例：日本溫泉三日遊", max_length=255
                    ),
                ),
                (
                    "location_country",
                    models.CharField(
                        help_text="請輸入行程的目的地國家名稱，例：日本", max_length=100
                    ),
                ),
                (
                    "location_city",
                    models.CharField(
                        help_text="請輸入行程的目的地城市名稱，例：東京", max_length=100
                    ),
                ),
                (
                    "price_ntd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="行程的價格，預設為新台幣",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="TWD", help_text="幣別", max_length=10),
                ),
                (
                    "min_group_size",
                    models.IntegerField(help_text="此行程最少需要的成團人數"),
                ),
                (
                    "features",
                    models.TextField(
                        help_text="行程的特色或亮點，例：溫泉、滑雪、觀光等"
                    ),
                ),
                (
                    "promotions",
                    models.TextField(
                        help_text="行程的優惠措施，例：早鳥優惠、組合套餐優惠等"
                    ),
                ),
                (
                    "flight_reference",
                    models.TextField(
                        help_text="參考航班資料，包含去程和回程的航班資訊，格式為JSON"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(help_text="行程的具體出發日期")),
                (
                    "token_amount",
                    models.IntegerField(help_text="此日期時段所發行的代幣數量"),
                ),
                (
                    "available_spots",
                    models.IntegerField(help_text="此日期時段可預訂的名額數"),
                ),
                (
                    "price_ntd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="此日期時段的價格（NTD），與基本行程價格可能不同",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "開放預訂"),
                            ("CLOSED", "已關閉預訂"),
                            ("FULL", "已滿額"),
                        ],
                        default="OPEN",
                        help_text="日期時段的狀態，例：開放預訂、已關閉預訂、已滿額",
                        max_length=10,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="此日期時段所屬的行程",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="trip.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token_amount",
                    models.IntegerField(help_text="此日期時段發行的代幣數量"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNISSUED", "尚未發行"),
                            ("ISSUED", "已發行"),
                            ("SOLD_OUT", "已售罄"),
                        ],
                        default="UNISSUED",
                        help_text="代幣的狀態，例：尚未發行、已發行、已售罄",
                        max_length=10,
                    ),
                ),
                (
                    "trip_schedule",
                    models.ForeignKey(
                        help_text="此代幣所屬的日期時段",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="trip.tripschedule",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tripschedule",
            index=models.Index(fields=["trip"], name="trip_tripsc_trip_id_dac2df_idx"),
        ),
    ]
