# Generated by Django 5.2 on 2025-04-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tripschedule",
            old_name="token_amount",
            new_name="token_index",
        ),
        migrations.AlterField(
            model_name="triptoken",
            name="token_amount",
            field=models.IntegerField(help_text="此日期時段發行的第 x 顆代幣"),
        ),
    ]
