# Generated by Django 5.2 on 2025-04-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0003_tripschedule_borrower"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tripschedule",
            old_name="borrower",
            new_name="sold",
        ),
    ]
