# Generated by Django 5.2 on 2025-04-26 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0004_rename_borrower_tripschedule_sold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tripschedule",
            name="sold",
        ),
        migrations.CreateModel(
            name="TripOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "spots_booked",
                    models.IntegerField(default=1, help_text="訂購的名額數"),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待付款"),
                            ("PAID", "已付款"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "trip_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trip.tripschedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tripschedule",
            name="sold_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="purchased_tripschedules",
                through="trip.TripOrder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
