# Generated by Django 5.2 on 2025-05-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0005_remove_tripschedule_sold_triporder_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="triporder",
            options={"permissions": [("can_purchase_trip", "Can purchase trip")]},
        ),
    ]
