# Generated by Django 5.2 on 2025-05-10 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("trip", "0006_alter_triporder_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripschedule",
            name="sold_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="purchased_tripschedules",
                through="order.TripOrder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="TripOrder",
        ),
    ]
