# Generated by Django 5.2 on 2025-05-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0008_trip_created_by_trip_is_active_trip_thumbnail_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TripToken",
        ),
    ]
