# Generated by Django 5.2 on 2025-05-18 14:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("tokens", "0001_initial"),
        ("trip", "0009_delete_triptoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="triptoken",
            name="token_index",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Sequence number of this token within its TripSchedule, starting at 1",
            ),
        ),
        migrations.AlterModelOptions(
            name="triptoken",
            options={
                "ordering": ("trip_schedule", "token_index"),
                "verbose_name": "Trip Token",
                "verbose_name_plural": "Trip Tokens",
            },
        ),
        migrations.AlterUniqueTogether(
            name="triptoken",
            unique_together={("trip_schedule", "token_index")},
        ),
        migrations.AddField(
            model_name="triptoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Record creation timestamp",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="triptoken",
            name="issued_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when token was minted", null=True
            ),
        ),
        migrations.AddField(
            model_name="triptoken",
            name="mint_tx_hash",
            field=models.CharField(
                blank=True,
                help_text="Blockchain transaction hash for minting",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="triptoken",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="The TripOrder that resulted in this token being sold",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tokens",
                to="order.triporder",
            ),
        ),
        migrations.AddField(
            model_name="triptoken",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="User who purchased this token",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="triptoken",
            name="sold_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when token was sold", null=True
            ),
        ),
        
        migrations.AddField(
            model_name="triptoken",
            name="token_uri",
            field=models.URLField(
                blank=True, help_text="URI to token metadata on chain (for NFTs)"
            ),
        ),
        migrations.AddField(
            model_name="triptoken",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Record last update timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="triptoken",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Primary key",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="triptoken",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNISSUED", "Not Minted"),
                    ("ISSUED", "Minted"),
                    ("SOLD", "Sold"),
                ],
                default="UNISSUED",
                help_text="Lifecycle status of the token",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="triptoken",
            name="trip_schedule",
            field=models.ForeignKey(
                help_text="Which schedule this token belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to="trip.tripschedule",
            ),
        ),
        migrations.AddIndex(
            model_name="triptoken",
            index=models.Index(
                fields=["trip_schedule", "status"],
                name="tokens_trip_trip_sc_22f30d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="triptoken",
            index=models.Index(fields=["owner"], name="tokens_trip_owner_i_70b243_idx"),
        ),
        migrations.RemoveField(
            model_name="triptoken",
            name="token_amount",
        ),
    ]
