# Generated by Django 5.2 on 2025-05-10 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trip", "0006_alter_triporder_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TripOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "spots_booked",
                    models.IntegerField(default=1, help_text="訂購的名額數"),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待付款"),
                            ("PAID", "已付款"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "trip_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trip.tripschedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [("can_purchase_trip", "Can purchase trip")],
            },
        ),
    ]
