# Generated by Django 5.2 on 2025-05-18 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("trip", "0009_delete_triptoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="triporder",
            options={},
        ),
        migrations.AlterField(
            model_name="triporder",
            name="booking_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the booking was made"
            ),
        ),
        migrations.AlterField(
            model_name="triporder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                help_text="Payment lifecycle status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="triporder",
            name="spots_booked",
            field=models.IntegerField(default=1, help_text="Number of seats booked"),
        ),
        migrations.AlterField(
            model_name="triporder",
            name="trip_schedule",
            field=models.ForeignKey(
                help_text="Which schedule was booked",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="trip.tripschedule",
            ),
        ),
        migrations.AlterField(
            model_name="triporder",
            name="user",
            field=models.ForeignKey(
                help_text="User who placed this order",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
